feat: add jstt plugin type
fastify/fastify-type-provider-json-schema-to-ts pull request #15
Opened 2022-07-30 00:27 UTC by Liam-Tait

Add plugin specifc types

- FastifyPluginAsyncJStT
- FastifyPluginCallbackJStT

I opted to use an acronym for the type name instead of for bbrevity. If the full name is prefered, I am happy to update.

- FastifyPluginAsyncJSONSchemaToTs
- FastifyPluginCallbackJSONSchemaToTs

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-07-30 00:29 UTC, Liam-Tait commented
No script for npm run benchmark, ran npm run test all ok.

2022-07-30 00:30 UTC, RafaelGSS requested changes

2022-07-30 00:30 UTC, RafaelGSS commented on index.ts
> + * FastifyPluginCallback with Typebox automatic type inference
The references to Typebox should be updated

2022-07-30 00:34 UTC, Liam-Tait commented on index.ts
> + * FastifyPluginCallback with Typebox automatic type inference
Fixed in 
[me, no I would never copy and paste code](https://github.com/fastify/fastify-type-provider-json-schema-to-ts/pull/15/commits/213cbf9bc9b6df6bad8fca67825b22e1336da98e)

2022-07-30 08:20 UTC, mcollina approved these changes
lgtm

2022-07-30 08:46 UTC, Uzlopak commented
@mcollina dont you think we should have the full name of the type and not an abbreviation?

2022-07-30 11:41 UTC, RafaelGSS approved these changes

2022-07-30 17:39 UTC, mcollina commented
I'm mostly don't care about names of types as I don't code in TS. If things are problematic we'll get feedback about it.

2022-07-30 17:49 UTC, Uzlopak commented
To be honest: I use typescript alot and I think he name of the type is bad. 

I would like to see them named longer. Maybe called them FastifyPluginAsyncInferTypeByJSONSchema or so.

2022-07-30 21:59 UTC, mcollina commented
Then let's make it longer.

2022-07-31 12:16 UTC, Liam-Tait commented
> I would like to see them named longer. Maybe called them FastifyPluginAsyncInferTypeByJSONSchema or so.

We would have to append `JSONSchemaToTs` instead of `JSONSchema` as this is JSONSchemaToTs specific and doesn't work with JSON schema alone / typebox / other jsonSchema helper functions.

I think `FastifyPluginAsyncInferTypeByJSONSchemaToTs` is overly verbose in real world usage. e.g.

```ts
const plugin: FastifyPluginAsyncInferTypeByJSONSchemaToTs = async (fastify, options) => {

}
```


I think there is value to have the naming of these types align with the typebox types and
future TypeProviders with `FastifyPluginAsync${Name}`

I' have updated this with the non abbreviated version for clarity.

```ts
const plugin: FastifyPluginAsyncJSONSchemaToTs = async (fastify, options) => {

}
```

2022-07-31 12:58 UTC, Uzlopak commented on README.md
> +const plugin: FastifyPluginAsyncJStT = async function (fastify, _opts) {
```suggestion
const plugin: FastifyPluginAsyncJsonSchemaToTs = async function (fastify, _opts) {
```

2022-07-31 13:48 UTC, Liam-Tait commented on README.md
> +const plugin: FastifyPluginAsyncJStT = async function (fastify, _opts) {
Fixed with [remove all abbreviations](https://github.com/fastify/fastify-type-provider-json-schema-to-ts/pull/15/commits/7baf464e96b5271d1a97fd4a5bd83d31b16e4b6d)

2022-08-04 11:26 UTC, Liam-Tait commented
@mcollina Types are updated removing the abbreviations. Believe ok to merge 👍

Cheers for the feedback everyone

2022-08-04 12:53 UTC, climba03003 approved these changes
LGTM.

2022-08-04 12:54 UTC, merged